# Generated by Django 4.1 on 2022-08-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chapter_id_alter_contact_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='course_id',
        ),
    ]
