# Generated by Django 4.1 on 2022-08-27 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chapter_id_alter_contact_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='chapter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chapter'),
        ),
    ]
