# Generated by Django 4.1 on 2022-08-28 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_question_course_id_remove_test_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='chapter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chapter'),
        ),
        migrations.AlterField(
            model_name='test',
            name='no_of_questions',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='test',
            name='subject_id',
            field=models.ManyToManyField(to='api.subject'),
        ),
    ]
