# Generated by Django 4.1 on 2022-08-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_test_chapter_id_alter_test_no_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explaination',
            field=models.TextField(),
        ),
    ]
